### PR TITLE
ipfs-npm = registry-mirror.next()

### PR DESCRIPTION
**Pull request by diasdavid**
> **WIP**

- [x] new UX design
- [x] get ipfs-blob-store with all the latest IPFS https://github.com/ipfs/ipfs-blob-store/pull/17
- **features**
  - [ ] ipnpm registry clone
    - [x] core functionality
    - [ ] spawn a daemon if none is available
    - [ ] option: seq-number
    - [x] option: flush
    - [x] option: ipfs
    - [ ] option: log
    - [x] bug https://github.com/ipfs/go-ipfs/issues/2918
  - [ ] ipnpm registry index publish
    - [ ] core functionality
    - [ ] spawn a daemon if none is available
    - [ ] option: ipfs
  - [ ] ipnpm registry index fetch
    - [ ] core functionality
    - [ ] spawn a daemon if none is available
    - [ ] option: ipfs
    - [ ] option: name
  - [ ] ipnpm daemon
    - [x] core functionality
    - [ ] spawn a daemon if none is available
    - [ ] option: ipfs
  - [ ] ipnpm install
    - [ ] core functionality
    - [ ] spawn a daemon if none is available
    - [ ] option: ipfs
- **other dependencies**
  - [ ] new version of ipfsd-ctl using bin-wrapper https://github.com/ipfs/js-ipfsd-ctl/issues/78

### CODE REVIEW

**Comment by diasdavid** [comment]
@dignifiedquire could you write a status update on what you found so far?

**Comment by dignifiedquire** [comment]
Current findings: I came close twice to finish a full clone of the registry and ipfs blew up underneath me. The first time I hadn't flushed at all, the second time I did flush but still after the crash and restart `files ls /` was returning nothingness. I am currently waiting for @whyrusleeping to investigate what the failure was.

**Comment by dignifiedquire** [comment]
So with the latest multicore updates the cloning process was speed up nicely such that we have now a full clone inside IPFS. 

I just published it here:

```sh
> ipfs name publish /ipfs/QmWtyxBrThZzZb5m9bdM9NN3WF6m4Vk85AukjzeQmhgnu6
Published to QmcmzV8FXsEfF5bQFf8vyJxhBZcV2SxTBApRcQbP5BQYGz: /ipfs/QmWtyxBrThZzZb5m9bdM9NN3WF6m4Vk85AukjzeQmhgnu6
```

The current repo size is about `1.7T` but the actual size is probably lower, given that there are things from previous attempts in there.

Pinning this root hash does destroy the daemon currently.

**Comment by dignifiedquire** [comment]
```
> ipfs files ls /npm-registry |wc -l
208677
```

**Comment by diasdavid** [comment]
@dignifiedquire what is the status on this? Last time I heard was that modules were not being properly stored anymore. I know you changed the cloner to a multicore one, might be because of that?

**Comment by dignifiedquire** [comment]
The status is, I started to write a fully tested cloner here: https://github.com/dignifiedquire/registry-cloner but I will need some time to finish it.

**Pull request closed without merging**
