### PR TITLE
Use the `ipfs-npm` name for the module

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
For https://github.com/ipfs-shipyard/npm-on-ipfs/issues/51

**Comment by diasdavid** [comment]
@achingbrain just noticed that with this new version, there are 0 tests.. not good. What's the plan?

**Comment by achingbrain** [comment]
I have mixed thoughts about 'npm' being in the name of this module.  We're all friends but it is the trademark of a private company.  npm has become synonymous with the registry which helps discovery, but the npm registry itself is an implementation of a [CommonJS Package Registry](http://wiki.commonjs.org/wiki/Packages/Registry) which can be used with yarn and whatever XYZ new registry tool.

At the very least, to comply with their [trademark policy](https://www.npmjs.com/policies/trademark) it should be `ipfs-npm-registry` but it's a bit of a mouthful so `registry-mirror` to me seemed ok.

**Comment by diasdavid** [comment]
Oh, good point. Thanks for catching that and bringing that up. Can you open a issue to track this rename proposal?

**Pull request merged**
